### ISSUE TITLE
Inventor 2018

### ISSUE THREAD

**Issue by Psychokiller1888** [Velleman/Vertex-Delta-CAD#1]
As you might know, Inventor is not free :)

Can you turn the files into printable technical plans for production? It's quickly made with Inventor, just... I don't have it...

**Comment by chuebsch** [comment]
There are stl files there for all parts. I think openScad and other freely available CAD programs might handle it. Which program are you using?

**Comment by Psychokiller1888** [comment]
I'm not talking about stl files...... I'm not gonna print a nozzle or whatever parts. I need some mechanical drawings, but I don't have inventor to open the inventor files to generate the machining drawings..... But as you can see, as usual Velleman doesn't answer

**Comment by chuebsch** [comment]
FreeCAD can handle .stp, .igs, stl files and is free: 
https://www.freecadweb.org/downloads.php
What CAD program are you using and which file format do you prefer?

**Comment by Psychokiller1888** [comment]
I'll give a shot at FreeCAD, thanks!
